runtime: nodejs10
env: standard

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1.7
  disk_size_gb: 10

handlers:
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /
    static_dir: client/build