runtime: nodejs10
env: standard

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1.7
  disk_size_gb: 10

handlers:
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /static/js/(.*)
    static_files: client/build/static/js/\1
    upload: client/build/static/js/.*
  - url: /static/css/(.*)
    static_files: client/build/static/css/\1
    upload: client/build/static/css/.*