version: "2"

services:
  client:
      image: webapp-client
      restart: always
      ports:
        - "3000:3000"
      volumes:
        - ./client:/client            - /client/node_modules        links:            - api        networks:            webappnetwork
